# Generated by Django 5.0.14 on 2026-06-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='Karnataka', max_length=100),
        ),
    ]
