# Generated by Django 5.0.14 on 2026-06-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_verified_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='Karnataka', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
